package de.unistuttgart.ipvs.pmp.xmlutil.validator.issue;

public enum AISIssueType {
    
    NAME_LOCALE_INVALID,
    NAME_LOCALE_MISSING,
    NAME_LOCALE_OCCURRED_TOO_OFTEN,
    NAME_EN_MISSING,
    NAME_EMPTY,
    
    DESCR_LOCALE_INVALID,
    DESCR_LOCALE_MISSING,
    DESCR_LOCALE_OCCURRED_TOO_OFTEN,
    DESCR_EN_MISSING,
    DESCR_EMPTY,
    
    SF_IDENTIFIER_MISSING,
    SF_IDENTIFIER_OCCURRED_TOO_OFTEN,
    SF_NO_SF_EXISTS,
    SF_AT_LEAST_TWO_SFS_CONTAIN_SAME_RRG_AND_RPS_WITH_SAME_VALUE,
    
    RRG_IDENTIFIER_MISSING,
    RRG_IDENTIFIER_OCCURRED_TOO_OFTEN,
    RRG_MINREVISION_MISSING,
    RRG_MINREVISION_INVALID,
    RRG_NO_RRG_EXISTS,
    
    RPS_IDENTIFIER_MISSING,
    RPS_IDENTIFIER_OCCURRED_TOO_OFTEN,
    RPS_NO_RPS_EXISTS
    
}
